[build]
    publish = "dist"
    command = "pnpm run build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
    for = "/manifest.webmanifest"
    [headers.values]
        Content-Type = "applications/manifestt+json"

[[headers]]
    for = "/assets/*"
    [headers.values]
        cache-control = '''
        immutable
        '''